### ISSUE TITLE
Insanely low fps in cs2

### ISSUE THREAD

**Issue by nnra6864** [VirtCode/hypr-dynamic-cursors#10]
I am mainly experiencing this in the cs2 **menu**.
As soon as I disable dynamic cursors, the fps goes back to normal.
Just having it enabled makes my game run at like 5 fps when focused.
The game actually runs just fine but as soon as I open any kind of gui that supports mouse interaction(pause menu, main menu, scoreboard etc.) it just dies.

**Comment by VirtCode** [comment]
Not good, does that happen with any other programs/games too or is it only cs2?

Could you also try the following:
- disable hardware cursors (`cursor:no_hardware_cursors`) and see whether that changes something
- set `plugin:dynamic-cursors:hw_debug = true` (with hardware cursors enabled), and see how the cursor looks in a cs2 menu, and whether it changes color when the mouse is not moving

**Comment by nnra6864** [comment]
`cursor:no_hardware_cursors = true` fully fixed it!
Debug color is not changing when I am in a menu and being still.
I tried making a short vid in case I missed something but the debug just disappears as soon as obs starts capturing my screen with pipewire :/

**Comment by VirtCode** [comment]
> `cursor:no_hardware_cursors = true` fully fixed it!

okay that's something, at least there's a workaround. It's however not ideal because software cursors have a bit worse performance than hardware cursors. 

>  Debug color is not changing when I am in a menu and being still.

that seems normal behaviour then. `hw_debug` changes the color whenever a new shape is rendered, so it is correct that it doesn't change when not moved. 
The debug disappearing with obs is expected. Hyprland switches to software cursors when the screen is captured, and the hw_debug only colors the hardware cursor buffer.

does cs2 also lag if you are not moving the cursor? i.e. the buffer color isn't changing?
and does the problem also appear when you set this plugin's mode to `none`?

also, could you have a quick peek at the hyprland log, and see whether something suspicious is being spammed? just in case

I'll try to repro on my end later this week, so I don't have to ask so many questions anymore haha

**Comment by nnra6864** [comment]
> okay that's something, at least there's a workaround. It's however not ideal because software cursors have a bit worse performance than hardware cursors.

I see.

> that seems normal behaviour then. hw_debug changes the color whenever a new shape is rendered, so it is correct that it doesn't change when not moved.

Understood

> The debug disappearing with obs is also expected. Hyprland switches to software cursors when the screen is captured, and the hw_debug only colors the hardware cursor buffer.

That's a really interesting thing you brought up.
It could be the very reason some games lag when screensharing(oddly enough, not when capturing w obs and somebody has to actively be in your screenshare, otherwise it doesn't lag).
I mainly experienced this behaviour in Geometry Dash and Osu!
There was even a "cheating" situation that happened with a guy doing something consistently in gd when capturing with obs because that somehow made his game update less often.
This was on windows tho(no clue how hw/sw cursors are handled there) so I'll link it here if you are interested:
https://www.youtube.com/watch?v=YRjZchvCl84

> does cs2 also lag if you are not moving the cursor? i.e. the buffer color isn't changing?
and does the problem also appear when you set this plugin's mode to none?

1. No, if cursor is not moved, the game runs at a stable frame rate.
2. Setting it to `none` gets rid of the lag but I think I discovered a new bug XD
Even tho I set it to none, some apps(terminal, discord etc.) continued using the `rotate` mode, while others(firefox, cs2 etc.) switched to `none`.
This could be caused by the following line I am using:
`shaperule = default, rotate, rotate:offset: 21`
And as you mentioned in the readme, some apps use a different kind of cursor so this shaperule doesn't affect them(pretty sure firefox and cs2 are those apps).

> also, could you have a quick peek at the hyprland log, and see whether something suspicious is being spammed? just in case

I don't think there's anything weird about it but I could be missing something.

> I'll try to repro on my end later this week, so I don't have to ask so many questions anymore haha

No worries, glad I could help a bit!

**Comment by VirtCode** [comment]
>  This was on windows tho(no clue how hw/sw cursors are handled there) so I'll link it here if you are interested:

haha this is indeed very interesting. Never knew geometry dash went this deep. Wouldn't play gd on hyprland then, the frame scheduling is way too inconsistent there, even without plugins.

> Setting it to none gets rid of the lag but I think I discovered a new bug XD

This is actually intended behaviour if I understood this correctly. As you mentioned you have a shape rule, which means that properties set in this rule are overridden when a given shape is active. Because you have specified `rotate` in your rule, even when the mode is set to none, this rule overrides the mode if the shape `default` is active. You could just not set the mode in the rule such that it does not override the mode setting (e.g. just `shaperule = default, rotate:offset: 21`).

<br>

But regarding the actual bug, everything seems normal as you describe it. So I don't really know what could cause this, or whether there is even a fix. I'll try to reproduce some time soon, but I first have to get steam and stuff working on a decent system (probably gonna take a bit longer than a week, am quite busy atm). I'll see what I can do then.

A workaround to make the game playable would currently be to use sw cursors, or just disabling the plugin manually (`hyprctl keyword plugin:dynamic-cursors:enabled false`) when playing. Or I could also maybe add a window rule which disables the plugin, but this would be just a temporary fix anyway.

Also, If anyone else using this plugin can or can't reproduce this, please let us know.

**Comment by nnra6864** [comment]
> haha this is indeed very interesting. Never knew geometry dash went this deep. Wouldn't play gd on hyprland then, the frame scheduling is way too inconsistent there, even without plugins.

Yeah, gd has grown a lot in the past few years.
I am not too bothered by frame skipping because I play it for fun, good to know tho.

> This is actually intended behaviour if I understood this correctly.

I see, yeah I thought of it being an intended behaviour but better make sure it's not a bug

> But regarding the actual bug, everything seems normal as you describe it.

Yeah, it does, who knows what's actually going on tbh.

> probably gonna take a bit longer than a week, am quite busy atm

No hurry, disabling the plugin while playing cs works just fine and isn't a big deal at all, gl figuring it out.

> A workaround to make the game playable would currently be to use sw cursors, or just disabling the plugin manually

Yep, I just do `hyprpm disable dynamic-cursors`, that does the job.
I was thinking of making a bind but I don't play cs often enough for that.

**Comment by daki456** [comment]
> A friend just installed hyprland, I'll see if he's up to test it.
I have just tested and it works good to me without any lag

**Comment by nnra6864** [comment]
I'll close the issue since it's probably something on my end and debugging would be close to impossible.

**Comment by VirtCode** [comment]
Yeah, I thought some things might change when hyprland switches to aquamarine, but then aq doesn't really support hardware cursors on nvidia yet (which you seem to use if I go by your website?), so this plugin currently doesn't work for nvidia (with hw cursors) anyway.

But thanks for the report and sorry we couldn't really solve it, but as you said, debugging performance issues is really difficult, especially if you can't reproduce it yourself.

**Comment by nnra6864** [comment]
> hardware cursors on nvidia yet (which you seem to use if I go by your website?)

Showcase on my website is fairly outdated, I did switch to sw cursors now which works p much flawlessly tbh.

> this plugin currently doesn't work for nvidia (with hw cursors)

Other than the lag in cs, I didn't really have any issues.

> But thanks for the report and sorry we couldn't really solve it, but as you said, debugging performance issues is really difficult, especially if you can't reproduce it yourself.

No worries, you actually did resolve my issue by recommending software cursors, all's good now!
