### ISSUE TITLE
Rotate mode point up

### ISSUE THREAD

**Issue by nnra6864** [VirtCode/hypr-dynamic-cursors#4]
Hi, I enjoy using the rotate mode a lot, with the main issue being the default pointer tilt.
I tried fixing this myself by adding the following line to `/mode/ModeRotate.cpp` after all the calculations:
`angle += 30`
This did absolutely nothing tho.
I tried different values and subtracting instead, but nothing.
This would be a nice config option for people using the rotate mode.

**Comment by VirtCode** [comment]
Hmm, weird that those changes did not have any effect.

Anyways, I've implemented a quick config option under `plugin:dynamic-cursors:rotate:offset`, which is a clockwise offset applied to the angle in degrees. Hope this suits your needs.

As a sidenote, this is more of a temporary solution. Whilst a hard offset might look good with e.g. the pointer, the same offset won't look good with the e.g. text selector cursor. I plan to add shape dependent offsets etc. but that's probably gonna take a while and won't be entirely possible in all cases because wayland cursors are a mess (server- and clientside cursors).

**Comment by nnra6864** [comment]
Hi, thanks a lot for implementing this one!
I just tested it out and it works perfectly.
I find the value of 21 to work the best.
This is already a huge improvement but it'd be neat if it was applied to the default shape only.
I am glad to hear you are planning to implement that at some point and wish you the best of luck!

**Comment by VirtCode** [comment]
FYI, I've just implemented shape rules which allow specifying the offset on a per shape basis (as long as the shape is server side). See the section about them in the [readme](https://github.com/VirtCode/hypr-dynamic-cursors?tab=readme-ov-file#shape-rules).
