### ISSUE TITLE
Add option to change actual cursor size in shake

### ISSUE THREAD

**Issue by BeshoyEhab** [VirtCode/hypr-dynamic-cursors#40]
can you add option to run command like `hyprctl setcuror $CURRENT_CURSOR $SIZE_AFTER_ZOOM` to change the cursor size because when it increase in size to 5 times the original you will see pixels not cursor

and it will be great option.

> _if you have been add it tell me how it works_
> _it's optional to add this feature_

**Comment by VirtCode** [comment]
There already is an option to specify the size it will preload the high-resolution shapes as, `plugin:dynamic-cursors:hyprcursor:resolution`. You can set that to a higher value than the default (by default it is `<your-normal-cursor-size> * <shake-base-scale> * 1.5`. See the [hyprcursor section](https://github.com/VirtCode/hypr-dynamic-cursors?tab=readme-ov-file#hyprcursor) in the readme for more info.

Note however, that it is relatively expensive to load very high-resolution shapes, which means it will take longer to load the plugin, as hyprland will freeze during that time (loading 512px already takes over a second on my system).

**Comment by BeshoyEhab** [comment]
can you add example because when I edit it to any number it doesn't make any change

**Comment by VirtCode** [comment]
Hmm, sounds odd. The `resolution` value is documented in the README in the config section. Are you sure your hyprcursor theme is SVG-based?

If so, can you send your config for this plugin, and the logs when you try to change the resolution value, and notice no change?

**Comment by BeshoyEhab** [comment]
It works only in kitty and empty workspace but in apps like brave and waybar it return to pixelated mode

**Comment by VirtCode** [comment]
Ah yes, this is just brave and waybar using client-side cursors (waybar being GTK and Brave probably xwayland). This means these apps just hand over a raw texture to hyprland, to display as a cursor. As a result we cannot know which cursor shape it is and not load a higher resolution. There is nothing we really can do about that.

There is an option, `plugin:dynamic-cursors:hyprcursor:fallback` to set an explicit shape which is then shown instead of the pixelated original shape. See the [hyprcursor section in the readme](https://github.com/VirtCode/hypr-dynamic-cursors?tab=readme-ov-file#hyprcursor) for more information.

**Comment by BeshoyEhab** [comment]
Thank you very much.
