### ISSUE TITLE
Hyprland failed to load plugin

### ISSUE THREAD

**Issue by Permafrozen** [VirtCode/hypr-dynamic-cursors#44]
![image](https://github.com/user-attachments/assets/04ffd383-185e-427e-9c05-4402e48f25bf)

The plugin isn't loading after I updated my flake.

Hyprland:
```console
 >  hyprctl version
Hyprland 0.45.2 built from branch v0.45.2-b at commit 12f9a0d0b93f691d4d9923716557154d74777b0a  ([gha] Nix: update inputs).
Date: 2024-11-19
Tag: v0.45.2, commits: 12f9a0d0b93f691d4d9923716557154d74777b0a
built against aquamarine 0.5.0


flags set:
debug
```

Anyways still love the cursor plugin :D

**Comment by VirtCode** [comment]
hmm, are you using the package from nixpkgs? or if not, which commit is the plugin being built from?

**Comment by Permafrozen** [comment]
I am using my flake, here the .lock infos:

```lock
 "hypr-dynamic-cursors": {
 515   │       "inputs": {
 516   │         "hyprland": [
 517   │           "hyprland"
 518   │         ],
 519   │         "nixpkgs": "nixpkgs_2"
 520   │       },
 521   │       "locked": {
 522   │         "lastModified": 1733313300,
 523   │         "narHash": "sha256-d8uZATuT8fKNWSg1RCEzs2dkQaZsWscyGzYAiwh2xWM=",
 524   │         "owner": "VirtCode",
 525   │         "repo": "hypr-dynamic-cursors",
 526   │         "rev": "37c770dfb0667179174b26ba5b45618f1c2dd10b",
 527   │         "type": "github"
 528   │       },
 529   │       "original": {
 530   │         "owner": "VirtCode",
 531   │         "repo": "hypr-dynamic-cursors",
 532   │         "type": "github"
 533   │       }
 534   │     },
 ```
 
 ```lock
 "hyprland": {
 594   │       "inputs": {
 595   │         "aquamarine": "aquamarine",
 596   │         "hyprcursor": "hyprcursor",
 597   │         "hyprgraphics": "hyprgraphics",
 598   │         "hyprland-protocols": "hyprland-protocols",
 599   │         "hyprland-qtutils": "hyprland-qtutils",
 600   │         "hyprlang": "hyprlang",
 601   │         "hyprutils": "hyprutils",
 602   │         "hyprwayland-scanner": "hyprwayland-scanner",
 603   │         "nixpkgs": "nixpkgs_3",
 604   │         "pre-commit-hooks": "pre-commit-hooks",
 605   │         "systems": "systems",
 606   │         "xdph": "xdph"
 607   │       },
 608   │       "locked": {
 609   │         "lastModified": 1734005819,
 610   │         "narHash": "sha256-hbA0aFybdxjpu4Tr4xH57mOLjRMqcop6iBVA0ZFIIx4=",
 611   │         "owner": "hyprwm",
 612   │         "repo": "Hyprland",
 613   │         "rev": "aefaeedf5e3f773c923373795267c1633141566c",
 614   │         "type": "github"
 615   │       },
 616   │       "original": {
 617   │         "owner": "hyprwm",
 618   │         "repo": "Hyprland",
 619   │         "type": "github"
 620   │       }
 621   │     },
 ```
 
 I hope this helps. Feel free to ask for more information, but I am not sure what to provide that could be helpful. This is my whole configuration, but I don't think it is necessarily related to that: https://github.com/Permafrozen/dot-nixe

**Comment by VirtCode** [comment]
Okay I see, all stuff seems to be up-to-date. Just wanted to check, because the version currently on nixpkgs is broken.

Can you share an excerpt of the [hyprland log](https://wiki.hyprland.org/Crashes-and-Bugs/#getting-the-log) when the plugin is being loaded? You can also try to load it again using `hyprctl plugin load [absolute-so-file-path]` to get it in the logs. Maybe this will shed some light on what is going on.

**Comment by VirtCode** [comment]
Hmm, I don't use nix myself but I have a suspicion. I think you must be building the plugin against `-git`, but are trying to load the plugin in `v0.45.2`. Because the symbol that is missing seems to [exist on main](https://github.com/hyprwm/Hyprland/blob/61a51bb4ef5ff38a8482933da1756bf31d4475be/src/render/OpenGL.cpp#L1179C1-L1195C1) from what I can tell. It is also one of the functions that is not present in 0.45 (the Color type has changed). 

If the version info in the original post is correct, you seem to be running `v0.45.2`, built from `12f9a0d0b93f691d4d9923716557154d74777b0a`, but your flake is building the plugin against `aefaeedf5e3f773c923373795267c1633141566c` from what I can judge from your lockfile.

Is it possible that something like this is the case?

**Comment by Permafrozen** [comment]
That is weird, because it should build against the same version since I use the `follows` binding:

```
    hypr-dynamic-cursors = {
      url = "github:VirtCode/hypr-dynamic-cursors";
      inputs.hyprland.follows = "hyprland";
    };

    hyprland.url = "github:hyprwm/Hyprland";
```console

While writing this, I also updated the flake and tried again. Stil the same results. But if I look at the flake metadata and look at `hypr-dynamic-cursors` it says follows input `hyprland`:

```console
hypr-dynamic-cursors: github:VirtCode/hypr-dynamic-cursors/37c770dfb0667179174b26ba5b45618f1c2dd10b?narHash=sha256-d8uZATuT8fKNWSg1RCEzs2dkQaZsWscyGzYAiwh2xWM%3D (2024-12-04 11:55:00)
│   ├───hyprland follows input 'hyprland'
│   └───nixpkgs: github:nixos/nixpkgs/2768c7d042a37de65bb1b5b3268fc987e534c49d?narHash=sha256-AlcmCXJZPIlO5dmFzV3V2XF6x/OpNWUV8Y/FMPGd8Z4%3D (2024-10-23 06:41:50)
├───hyprland: github:hyprwm/Hyprland/3cba4ba44e7ba3cc8bb67ac71bc61245b5aca347?narHash=sha256-SSyk9SJ5Uu3/LhaoH2Bsgbx8fDgR6ZYQZG/13aNjL3M%3D (2024-12-13 22:36:42)
│   ├───aquamarine: github:hyprwm/aquamarine/4468981c1c50999f315baa1508f0e53c4ee70c52?narHash=sha256-TGcvIjftziC1CjuiHCzrYDwmOoSFYIhdiKmLetzB5L0%3D (2024-11-18 19:43:51)
│   │   ├───hyprutils follows input 'hyprland/hyprutils'
│   │   ├───hyprwayland-scanner follows input 'hyprland/hyprwayland-scanner'
│   │   ├───nixpkgs follows input 'hyprland/nixpkgs'
│   │   └───systems follows input 'hyprland/systems'
│   ├───hyprcursor: github:hyprwm/hyprcursor/0264e698149fcb857a66a53018157b41f8d97bb0?narHash=sha256-EDNAU9AYcx8OupUzbTbWE1d3HYdeG0wO6Msg3iL1muk%3D (2024-10-11 18:02:18)
│   │   ├───hyprlang follows input 'hyprland/hyprlang'
│   │   ├───nixpkgs follows input 'hyprland/nixpkgs'
│   │   └───systems follows input 'hyprland/systems'
│   ├───hyprgraphics: github:hyprwm/hyprgraphics/cc95e5babc6065bc3ab4cd195429a9900836ef13?narHash=sha256-FFLJzFTyNhS7tBEEECx0B8Ye/bpmxhFVEKlECgMLc6c%3D (2024-12-03 17:52:51)
│   │   ├───hyprutils follows input 'hyprland/hyprutils'
│   │   ├───nixpkgs follows input 'hyprland/nixpkgs'
│   │   └───systems follows input 'hyprland/systems'
│   ├───hyprland-protocols: github:hyprwm/hyprland-protocols/a7c183800e74f337753de186522b9017a07a8cee?narHash=sha256-xGbkc7U/Roe0/Cv3iKlzijIaFBNguasI31ynL2IlEoM%3D (2024-10-07 23:50:20)
│   │   ├───nixpkgs follows input 'hyprland/nixpkgs'
│   │   └───systems follows input 'hyprland/systems'
│   ├───hyprland-qtutils: github:hyprwm/hyprland-qtutils/969427419276c7ee170301ef1ebe0f68eb6eb2e2?narHash=sha256-PvXiFLIExJEJj%2BgoLbIuXLTN5CSDSAUsAfiYSdbbWg0%3D (2024-12-06 08:05:16)
│   │   ├───hyprutils follows input 'hyprland/hyprutils'
│   │   ├───nixpkgs follows input 'hyprland/nixpkgs'
│   │   └───systems follows input 'hyprland/systems'
│   ├───hyprlang: github:hyprwm/hyprlang/f054f2e44d6a0b74607a6bc0f52dba337a3db38e?narHash=sha256-AnB1KfiXINmuiW7BALYrKqcjCnsLZPifhb/7BsfPbns%3D (2024-10-05 22:50:12)
│   │   ├───hyprutils follows input 'hyprland/hyprutils'
│   │   ├───nixpkgs follows input 'hyprland/nixpkgs'
│   │   └───systems follows input 'hyprland/systems'
│   ├───hyprutils: github:hyprwm/hyprutils/b26f33cc1c8a7fd5076e19e2cce3f062dca6351c?narHash=sha256-XTU9B53IjGeJiJ7LstOhuxcRjCOFkQFl01H78sT9Lg4%3D (2024-11-22 15:11:21)
│   │   ├───nixpkgs follows input 'hyprland/nixpkgs'
│   │   └───systems follows input 'hyprland/systems'
│   ├───hyprwayland-scanner: github:hyprwm/hyprwayland-scanner/500c81a9e1a76760371049a8d99e008ea77aa59e?narHash=sha256-VKR0sf0PSNCB0wPHVKSAn41mCNVCnegWmgkrneKDhHM%3D (2024-09-20 23:27:16)
│   │   ├───nixpkgs follows input 'hyprland/nixpkgs'
│   │   └───systems follows input 'hyprland/systems'
│   ├───nixpkgs: github:NixOS/nixpkgs/d0797a04b81caeae77bcff10a9dde78bc17f5661?narHash=sha256-kEsTJTUQfQFIJOcLYFt/RvNxIK653ZkTBIs4DG%2BcBns%3D (2024-12-05 09:53:19)
│   ├───pre-commit-hooks: github:cachix/git-hooks.nix/6f4e2a2112050951a314d2733a994fbab94864c6?narHash=sha256-SVQVsbafSM1dJ4fpgyBqLZ%2BLft%2BjcQuMtEL3lQWx2Sk%3D (2024-12-04 13:28:28)
│   │   ├───flake-compat: github:edolstra/flake-compat/0f9255e01c2351cc7d116c072cb317785dd33b33?narHash=sha256-kvjfFW7WAETZlt09AgDn1MrtKzP7t90Vf7vypd3OL1U%3D (2023-10-04 13:37:54)
│   │   ├───gitignore: github:hercules-ci/gitignore.nix/637db329424fd7e46cf4185293b9cc8c88c95394?narHash=sha256-HG2cCnktfHsKV0s4XW83gU3F57gaTljL9KNSuG6bnQs%3D (2024-02-28 02:28:52)
│   │   │   └───nixpkgs follows input 'hyprland/pre-commit-hooks/nixpkgs'
│   │   ├───nixpkgs follows input 'hyprland/nixpkgs'
│   │   └───nixpkgs-stable: github:NixOS/nixpkgs/d063c1dd113c91ab27959ba540c0d9753409edf3?narHash=sha256-edm8WG19kWozJ/GqyYx2VjW99EdhjKwbY3ZwdlPAAlo%3D (2024-11-04 17:24:30)
│   ├───systems: github:nix-systems/default-linux/31732fcf5e8fea42e59c2488ad31a0e651500f68?narHash=sha256-12tWmuL2zgBgZkdoB6qXZsgJEH9LR3oUgpaQq2RbI80%3D (2023-07-14 15:19:09)
│   └───xdph: github:hyprwm/xdg-desktop-portal-hyprland/fd85ef39369f95eed67fdf3f025e86916edeea2f?narHash=sha256-NetqJHAN4bbZDQADvpep%2BwXk2AbMZ2bN6tINz8Kpz6M%3D (2024-12-02 16:31:04)
│       ├───hyprland-protocols follows input 'hyprland/hyprland-protocols'
│       ├───hyprlang follows input 'hyprland/hyprlang'
│       ├───hyprutils follows input 'hyprland/hyprutils'
│       ├───hyprwayland-scanner follows input 'hyprland/hyprwayland-scanner'
│       ├───nixpkgs follows input 'hyprland/nixpkgs'
│       └───systems follows input 'hyprland/systems'
```

Here you can also see they should be the same in the flake:

![image](https://github.com/user-attachments/assets/bbce2e72-5d4f-41c1-bfdd-1c87d14dde66)

I am kinda running out of ideas what could be the reason for this.

**Comment by VirtCode** [comment]
But the version reported by `hyprctl version` in a running session is still `v0.45.2` right? 

Maybe @bloxx12 can have a look at this, he did the nix stuff for this plugin.

**Comment by bloxx12** [comment]
Weird idea, but can you try adding
`inputs.nixpkgs.follows = "nixpkgs"`?

**Comment by bloxx12** [comment]
Hmmm, weird problem. Flake input looks correct, your config as well. 
One idea: try adding
`inputs.nixpkgs.follows = "nixpkgs"` 
to the `hypr-dynamic-cursors` input.
*Maybe* that'll help?

**Comment by Permafrozen** [comment]
> Hmmm, weird problem. Flake input looks correct, your config as well. One idea: try adding `inputs.nixpkgs.follows = "nixpkgs"` to the `hypr-dynamic-cursors` input. _Maybe_ that'll help?

I did updated my flake inputs again and used `inputs.nixpkgs.follows = "nixpkgs"`, but it still fails to load. @bloxx12 does it work for you? If so do you have any other ideas?

**Comment by VirtCode** [comment]
@Permafrozen you might want to try building again, we just saw that the flake was using an older gcc version than the other hypr* stuff, so maybe this is also the problem here?

If not, can you confirm that the version that `hyprctl version` outputs is actually what you are trying to use in the flake? Cause in the OP this didn't seem to be the case.

**Comment by Permafrozen** [comment]
Hello, sorry for the late reply.

I updated my flake and rebuild but sadly I still have the same issue. I am now on hyprland `0.46.2 built from branch v0.46.2-b at commit 0bd541f2fd902dbfa04c3ea2ccf679395e316887  (version: bump to 0.46.2)`. If you get any idea what it could be/what could help let me know. Thanks for the help.

**Comment by VirtCode** [comment]
I think the problem here is that you are running a different version of hyprland than what your flake is targetting. I don't really know nix, so correct me if I'm wrong. But if you are building the plugin against the hyprland flake (which follows -git right?), and try to load it in your session which you say is on `0.46.2`, it of course won't work. If you are using hyprland from nixpkgs, I would probably also use the plugin from nixpkgs (it is on there I think).

I don't know for sure whether this is the problem, but you could check the following:
1. Enable the plugin in your flake and rebuild the system.
2. Start hyprland and observe the error message (i.e. `Failed to load ...`)
3. Check your running hyprland commit with `hyprctl version`
4. Check the commit the plugin is built against with `strings /nix/store/<the hash thingy>/libhypr-dynamic-cursors.so | grep -E "^[a-f0-9]{40}$"`. Make sure you check **the hash that is shown in the error message from hyprland**.
5. See whether the two commits match and compare these revisions with your flake lockfile.

**Comment by Permafrozen** [comment]
I am not to sure myself, but I just tried a bunch of things, after using the plugin's nix package it worked, but it doesn't make sense for me since I am using the hyprland flake and I don't understand anything anymore what the hell.
