### ISSUE TITLE
Can't represent shake settings in Nix

### ISSUE THREAD

**Issue by RGBCube** [VirtCode/hypr-dynamic-cursors#7]
![image](https://github.com/VirtCode/hypr-dynamic-cursors/assets/78925721/c4ca9805-d19a-4a80-bc6a-fe286e7ea995)

See the problem? yeah

Maybe do the enable setting like `stretch:enabled`

Also maybe `rotate:enabled`, `stretch:enabled` and so instead of a mode toggle. And you could check for only one or none being enabled.

Great work btw! I'm going to create a hyprcursor theme that is optimized for rotation soon to complement this.

**Comment by VirtCode** [comment]
Oh I see, didn't really account for nix when creating the config.
I'll move the `shake` setting to `shake:enabled`, shouldn't be too breaking as shake is enabled by default and I assume most people leave it enabled. Otherwise you quickly notice that it is on again.

Regarding the `mode` setting, I think I want to keep it as a single setting, as this implicitly tells the user that the modes are exclusive, so you can't even try enabling multiple. In the future I also want to be able to set a per-shape mode, so having `enabled` properties in the mode sections would be a bit confusing.

Also, let me know about your cursor theme once you finish it, sounds interresting. Maybe I make the effort to switch away from default adwaita cursors haha.
