### ISSUE TITLE
Error: mismatched headers

### ISSUE THREAD

**Issue by arthsmn** [VirtCode/hypr-dynamic-cursors#9]
I'm trying to install this plugin via NixOS. I've added the input and put it into plugins in my hyprland home-manager config. But, when I rebuild my system it says that the plugin has mismatched headers, and idk how to fix or test the problem. I would be glad to help debugging. Running latest version of NixOS, home-manager and hyprland flakes.

**Comment by VirtCode** [comment]
The mismatched headers error is shown when the plugin was built for a certain commit of hyprland, but is trying to load on a running hyprland instance on another commit. So this usually happens when you have built the plugin, then update hyprland  and try to load the plugin without rebuilding the plugin for the newer hyprland version first.

Is it possible that something like this happened on your end? I don't know much about nix and how stuff works there, so I don't know where such an issue could be caused.

**Comment by arthsmn** [comment]
I think this is not the case, as I set the hyprland input to follow my hyprland, as the example in the readme suggests. Also, I haven't done any updates right now, and I'm pretty sure that the plugin would be rebuilt automatically if hyprland updates.

**Comment by VirtCode** [comment]
Pushed an extra notif which will show the built and running headers. Could you try build again and look which commit the plugin was built with? Maybe we can notice something this way.

**Comment by arthsmn** [comment]
Hey, sorry for the trouble! The home-manager module was overwriting my nixos hyprland config and using the nixpkgs version, so I just needed to set package = inputs... and it worked like it should. Thanks!

**Comment by VirtCode** [comment]
no worries, glad it works!
